import type { Metadata } from "next";
import {Inter } from "next/font/google"
import "./globals.css";
import { TanstackProvider } from "@/components/providers/tanstackquery-provider";
import Container from "@/components/common/container";
import { ThemeProvider } from "@/components/providers/theme-provider";

const geistSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      suppressHydrationWarning
        className={`antialiased`}
      >
        <ThemeProvider>
        <TanstackProvider>    
        {children}
        </TanstackProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
